spring:
  application:
    name: ushort
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    spring.jpa.database-platform: ${DB_DIALECT}
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: update